spring:
  cloud:
    name:
      CONFIG
    config:
      server:
        native:
           search-locations: F:/work/ecommerce/configserver/src/main/resources/config
#logging:
#  level:
#    com.netflix.discovery: 'OFF'
#    org.springframework.cloud: 'DEBUG'    